apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chack-landing-ingress
  labels:
    app: chack-landing
spec:
  ingressClassName: nginx
  rules:
  - host: chack-check.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chack-landing-service
            port:
              number: 3000