name: CI/CD Prod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-landing:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-landing:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://master.k8s.chack-check.ru:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy app
        uses: azure/k8s-deploy@v1
        with:
          namespace: landing
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-landing:${{ github.sha }}
